services:
  discord-bot:
    build: 
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    container_name: assembly-discord-tracker
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-3000}:3000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - WEB_PORT=3000
      - DATABASE_PATH=/app/data/discord_stats.db
      - NODE_ENV=${NODE_ENV:-production}
      - EVENT_NAME=${EVENT_NAME}
      - EVENT_START_DATE=${EVENT_START_DATE}
      - EVENT_END_DATE=${EVENT_END_DATE}
      - EVENT_TIMEZONE=${EVENT_TIMEZONE}
      - EVENT_DESCRIPTION=${EVENT_DESCRIPTION}
    volumes:
      - discord_data:/app/data
      # WSL compatibility: Use named volume instead of bind mount for better performance
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - discord-tracker

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: assembly-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - certbot_certs:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    depends_on:
      - discord-bot
    networks:
      - discord-tracker
    profiles:
      - production

  # Certbot for automatic SSL certificate management
  certbot:
    image: certbot/certbot:latest
    container_name: assembly-certbot
    restart: "no"
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - ./scripts:/scripts:ro
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - discord-tracker
    profiles:
      - production

volumes:
  discord_data:
  certbot_certs:
  certbot_www:
    driver: local

networks:
  discord-tracker:
    driver: bridge
